### ISSUE TITLE
Drop pyup support

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/urihandler#75]
We're removing that everywhere

**Comment by goessebr** [comment]
Dag @koenedaele 

In https://pyup.io/account/repos/github/OnroerendErfgoed/urihandler/ kan ik de de repo niet verwijderen omdat jij die hebt toegevoegd. Wil jij die verwijderen?
![image](https://user-images.githubusercontent.com/1926276/173815299-2f589a81-3424-452c-b295-ba09e52c3163.png)


Scope voor ontwikkelaars: verwijderen van .pyup.yml uit de repo

**Comment by koenedaele** [comment]
Removed all repositories I could remove. Only left those I didn't add myself.
