### ISSUE TITLE
Is setup.cfg still needed?

### ISSUE THREAD

**Issue by koenedaele** [OnroerendErfgoed/urihandler#76]
Is this still doing anything since we're only supporting Python 3 now?

**Comment by goessebr** [comment]
We still support python 2 for now but via #80 we will drop the support and the new release will only support python 3. That means that the content of setup.cfg is indeed no longer needed.

Current content:
```
[bdist_wheel]
universal = 1
```

We could use an empty setup.cfg file or delete the file completely.

**Comment by roefem** [comment]
setup.cfg was removed in #82
